before_script: curl -s http://dingdemo.ngrok.io/building
script: sleep 10
after_success: 
  - curl -s http://dingdemo.ngrok.io/ding
  - curl -s http://dingdemo.ngrok.io/success
after_failure: 
  - curl -s http://dingdemo.ngrok.io/ding
  - curl -s http://dingdemo.ngrok.io/failure
